

security:
  oauth2:
    resource:
      accessTokenUri: http://localhost:9000/oauth/token
      userAuthorizationUri: http://localhost:9000/oauth/authorize
      userInfoUri: http://localhost:9000/users/user
      client:
        client-id: clientapp
        client-secret: 123456
        scope: read,write
        auto-approve-scopes: '.*'
        tokenInfoUri: http://localhost:9000/oauth/token
